affairs <- read.csv("Affairs.csv")
head(Affairs,5)
tail(Affairs,5)
summary(Affairs$age)
summary(Affairs$gender)
summary(Affairs$children)
summary(Affairs$religiousness)
sd(Affairs$age,na.rm = TRUE)
sd(Affairs$yearsmarried,na.rm = TRUE)
sd(Affairs$age,na.rm = TRUE)
sd(Affairs$affairs,na.rm = TRUE)
var(Affairs$age)
var(Affairs$yearsmarried)
var(Affairs$education)
var(Affairs$affairs)
plot(Affairs$affairs)
plot(Affairs$education)
plot(Affairs$yearsmarried,type = "b")
barplot(Affairs$affairs)
barplot(Affairs$yearsmarried,col = "green", main = "Affairs",)
barplot(Affairs$age,col = "blue",main = "Affairs")
hist(Affairs$rating,col = "green",main = "Affairs")
hist(Affairs$affairs,col = "orange",main = "Affairs")

hist(Affairs$yearsmarried,col = "green", main = "Affairs")
hist(Affairs$age,col = "pink",main = "Affairs")
boxplot(Affairs$occupation,col = "red", main = "Affairs")
boxplot(Affairs$yearsmarried,Affairs$affairs,col = "yellow",main = "Affairs")
scatter.smooth(Affairs$age, type = "l")
scatter.smooth(Affairs$rating,type = "l")
skewness(Affairs$affairs)
skewness(Affairs$age)
skewness(Affairs$yearsmarried)
kurtosis(Affairs$occupation)
kurtosis(Affairs$education)
scale(Affairs$affairs,10)
scale(Affairs$occupation,5)

