dad <- datasets::ChickWeight 
head(dad,10)
tail(dad,19)
dad
summary(dad)
sd(dad$weight)
sd(dad$Time)
var(dad$weight)
var(dad$Time)
mode(dad$weight)
mode(dad$Time)
mfv(dad$weight)
mfv(dad$Time)
range(dad$weight)
range(dad$Time)
range(dad$Chick)
skewness(dad$weight)
skewness(dad$Time)
kurtosis(dad$weight)
kurtosis(dad$Time)
hist(dad$weight)
hist(dad$Time,col = "blue")
boxplot(dad$weight)
boxplot(dad$Time)
boxplot(dad$weight)$out
barplot(dad$weight)
barplot(dad$Time)
qqnorm(dad$weight)
qqline(dad$weight)
qqnorm(dad$Time)
qqline(dad$Time)
attach(dad)
summary(standard_values)
normalize = function(x){
  return ((x-min(x))/(max(x)-min(x)))
}
