gas<-read.csv("NaturalGas.csv")
head(10)
tail(5)
summary(NaturalGas)
summary(NaturalGas$state)
summary(NaturalGas$statecode)
summary(NaturalGas$year)
Summary(NaturalGas$income)
plot(NaturalGas)
plot(NaturalGas$state)
plot(NaturalGas$statecode,col = "blue",main = "naturalgas")
barplot(NaturalGas$year,col = "yellow",main = "naturalgas")
barplot(NaturalGas$statecode,col = "green",main = "NaturalGas")
barplot(NaturalGas$price)
qqnorm(NaturalGas$price)
qqline(NaturalGas$price)
qqnorm(NaturalGas$oprice)
qqnorm(NaturalGas$oprice)
qqline(NaturalGas$oprice)
hist(NaturalGas$price,col = "pink")
hist(NaturalGas$eprice,col = "green",main = "naturalGas",xlab = "Frequency",ylab = "eprice")
hist(NaturalGas$oprice,col = "gold",main = "NaturalGas",xlab = "Oprice",ylab = "oprice")
skewness(NaturalGas$price)
skewness(NaturalGas$eprice)
skewness(NaturalGas$oprice)
kurtosis(NaturalGas$price)
kurtosis(NaturalGas$eprice)
kurtosis(NaturalGas$oprice)
boxplot(NaturalGas$price,col = "green",main = "Naturalgas")
boxplot(NaturalGas$eprice,col = "orange",main = "naturalgas")
scatter.smooth(NaturalGas$price,col="pink",main ="naturalgas")
scatter.smooth(NaturalGas$eprice,col ="blue",main = "naturalgas")
sd(NaturalGas$price)
sd(NaturalGas$eprice,na.rm = "True")
sd(NaturalGas$oprice,na.rm = "True")  
sd(NaturalGas$eprice,na.rm = "True")
