shal <- datasets::USArrests
head(shal,10)
tail(shal,10)
df<-shal
summary(shal)
summary(shal$Murder)
summary(shal$Assault)
summary(shal$UrbanPop)
summary(shal$Rape)
plot(shal)
barplot(shal$Murder,main = "usa murders",col = "red",type = "l")
barplot(shal$Assault,main = "usa murders",col = "pink")
hist(shal$UrbanPop,main = "usa murders",col = "blue")
hist(shal$Rape,main = "usa murders",col = "black")
boxplot(shal$Murder)
boxplot(shal$Rape,shal$UrbanPop,col = "yellow")
scatter.smooth(shal$Assault,col = "brown")
scale.default(shal)
scale.default(shal$UrbanPop)
scale(shal)
scatter.smooth(shal$Rape,col = "green",main = "usa murders")
scatter.smooth(shal$UrbanPop,col = "yellow")
